import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./components/Providers";
import Navbar from "./components/Navbar";
import Script from "next/script";
import "react-datepicker/dist/react-datepicker.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html className="light" lang="en">
      <head>
        <Script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></Script>
      </head>
      <body
        className={`flex flex-col min-h-screen w-full bg-gradient-to-t from-[#0a081a] to-[#1c1649] ${inter.className}`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
